# Κάνοντας compile το <foo>_test.c με μια υλοποίηση <foo>.c του
# συγκεκριμένου τύπου, παράγουμε ένα tets για την υλοποίηση αυτή.

# Υλοποιήσεις μέσω HashTable: ADTMap
#
UsingHashTable_ADTMap_test_OBJS		= ADTMap_test.o $(MODULES)/UsingHashTable/ADTMap.o

# Υλοποιήσεις μέσω HopscotchHash: ADTMap
#
UsingHopscotchHash_ADTMap_test_OBJS	= ADTMap_test.o $(MODULES)/UsingHopscotchHash/ADTMap.o

# Υλοποιήσεις μέσω HybridHash: ADTMap
#
UsingHybridHash_ADTMap_test_OBJS	= ADTMap_test.o $(MODULES)/UsingHybridHash/ADTMap.o $(MODULES)/UsingDynamicArray/ADTVector.o


# Ο βασικός κορμός του Makefile
include ../common.mk